server:
  port: 80
spring:
  datasource:
    druid:
      username: root #不会真有傻逼写成name吧
      password: 1234
      url: jdbc:mysql://localhost:3306/frog?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver #Driver的D要大写
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto #没有这行id就是乱码
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
